# Generated by Django 2.2.2 on 2019-06-19 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 19, 55, 24, 786308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 19, 55, 24, 784308, tzinfo=utc)),
        ),
    ]
