# Generated by Django 2.2.2 on 2019-06-19 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190620_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 21, 3, 26, 271408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 19, 21, 3, 26, 269408, tzinfo=utc)),
        ),
    ]
