# Generated by Django 2.1.1 on 2019-08-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190802_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
